server:
 port: 8081
logging:
  level:
    '[org.springframework]': debug 
spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;    
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    